export const SET_USER_DATA = 'SET_USER_DATA';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const SET_GENERATORS = 'SET_GENERATORS';
export const CLEAR_GENERATORS = 'CLEAR_GENERATORS';
// export const TASK_ADD = 'TASK_ADD';
// export const TASK_TOGGLE = 'TASK_TOGGLE';
// export const TASK_REMOVE = 'TASK_REMOVE';